"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/utils";
import { toast } from "sonner";
import {
  Wallet, Plus, Trash2, ChevronDown, ChevronRight,
  Play, Printer, Users, X, Percent, DollarSign,
} from "lucide-react";
import {
  computePayslip, type PayrollConfig, type CustomDeduction, type Payslip,
  SSNIT_EMPLOYEE_RATE, SSNIT_EMPLOYER_RATE,
} from "@/lib/ghana-payroll";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

// ── helpers ──────────────────────────────────────────────────────
function newId() { return Math.random().toString(36).slice(2); }

const MONTHS = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

function currentPeriod() {
  const d = new Date();
  return `${MONTHS[d.getMonth()]} ${d.getFullYear()}`;
}
function monthValue(period: string) {
  const [m, y] = period.split(" ");
  const idx = MONTHS.indexOf(m);
  return `${y}-${String(idx + 1).padStart(2, "0")}`;
}

// ── Payslip Print ────────────────────────────────────────────────
function printPayslip(ps: Payslip, schoolName: string) {
  const row = (l: string, v: string, bold = false, red = false, green = false) =>
    `<tr style="border-bottom:1px solid #eee">
      <td style="padding:6px 8px;font-size:13px;color:#555">${l}</td>
      <td style="padding:6px 8px;text-align:right;font-size:13px;font-weight:${bold?"700":"500"};color:${red?"#dc2626":green?"#16a34a":"#111"}">${v}</td>
    </tr>`;

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Payslip ${ps.period}</title>
  <style>body{font-family:system-ui,Arial,sans-serif;max-width:480px;margin:24px auto;color:#111}
  h2{margin:0;font-size:20px}p{margin:2px 0;font-size:12px;color:#555}table{width:100%;border-collapse:collapse}
  .section{font-size:11px;font-weight:700;color:#888;letter-spacing:.06em;text-transform:uppercase;padding:8px 8px 4px;background:#f8f9fa}
  @media print{body{margin:0}}</style></head>
  <body>
    <div style="border-bottom:3px solid #0D6B3B;padding-bottom:12px;margin-bottom:16px">
      <h2>${schoolName}</h2><p>Payslip — ${ps.period}</p><p>Employee: <strong>${ps.teacher_name}</strong></p>
    </div>
    <table>
      <tr class="section"><td colspan="2">Earnings</td></tr>
      ${row("Basic Salary", formatCurrency(ps.basic_salary))}
      ${ps.total_allowances > 0 ? row("Total Allowances", formatCurrency(ps.total_allowances)) : ""}
      ${row("Gross Pay", formatCurrency(ps.gross_pay), true)}
      <tr class="section"><td colspan="2">Deductions</td></tr>
      ${row(`SSNIT (${(SSNIT_EMPLOYEE_RATE*100).toFixed(1)}% of basic)`, `(${formatCurrency(ps.ssnit_employee)})`, false, true)}
      ${row(`PAYE (on GHS ${ps.chargeable_income.toFixed(2)})`, `(${formatCurrency(ps.paye)})`, false, true)}
      ${ps.custom_deductions.map((d) => row(d.label, `(${formatCurrency(d.amount)})`, false, true)).join("")}
      ${row("Total Deductions", `(${formatCurrency(ps.total_deductions)})`, true, true)}
      <tr class="section"><td colspan="2">Net Pay</td></tr>
      ${row("NET PAY", formatCurrency(ps.net_pay), true, false, true)}
      <tr class="section"><td colspan="2">Employer Cost (not deducted from employee)</td></tr>
      ${row(`SSNIT Employer (${(SSNIT_EMPLOYER_RATE*100).toFixed(0)}% of basic)`, formatCurrency(ps.ssnit_employer))}
      ${row("Total Employer Cost", formatCurrency(ps.total_employer_cost), true)}
    </table>
    <div style="margin-top:20px;border-top:1px dashed #ccc;padding-top:12px;font-size:11px;color:#888">
      Generated by Skuulr · Ghana payroll computed per GRA 2024 PAYE bands and SSNIT Act 766.
    </div>
    <script>window.onload=function(){window.print()}</script>
  </body></html>`;

  const w = window.open("", "_blank", "width=520,height=800");
  if (!w) { toast.error("Allow pop-ups to print payslips"); return; }
  w.document.write(html); w.document.close();
}

// ── Staff Config Card ────────────────────────────────────────────
function StaffConfigCard({
  config, teachers, onUpdate, onRemove,
}: {
  config: PayrollConfig;
  teachers: Array<{ id: string; first_name: string; last_name: string }>;
  onUpdate: (c: PayrollConfig) => void;
  onRemove: () => void;
}) {
  const [open, setOpen] = useState(false);
  const set = (key: keyof PayrollConfig, val: unknown) => onUpdate({ ...config, [key]: val });
  const gross = config.basic_salary + config.transport_allowance + config.housing_allowance +
    config.medical_allowance + config.responsibility_allowance + config.other_allowance;

  const addDeduction = () => {
    const d: CustomDeduction = { id: newId(), label: "", type: "fixed", value: 0 };
    onUpdate({ ...config, custom_deductions: [...(config.custom_deductions ?? []), d] });
  };
  const updateDeduction = (id: string, patch: Partial<CustomDeduction>) => {
    onUpdate({ ...config, custom_deductions: config.custom_deductions.map((d) => d.id === id ? { ...d, ...patch } : d) });
  };
  const removeDeduction = (id: string) => {
    onUpdate({ ...config, custom_deductions: config.custom_deductions.filter((d) => d.id !== id) });
  };

  const currentTeacher = teachers.find((t) => t.id === config.teacher_id);

  return (
    <div className="rounded-xl border border-gray-200 bg-white overflow-hidden">
      <button type="button" onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center gap-3 p-4 text-left hover:bg-gray-50 cursor-pointer">
        <div className="flex h-9 w-9 items-center justify-center rounded-lg flex-shrink-0"
          style={{ background: "hsl(150 30% 95%)" }}>
          <Users className="h-4 w-4" style={{ color: "hsl(150 80% 24%)" }} />
        </div>
        <div className="flex-1 min-w-0">
          <p className="font-semibold text-sm text-gray-900">{config.teacher_name || "Unnamed staff"}</p>
          <p className="text-xs text-gray-500">Gross: {formatCurrency(gross)} · Net est.: {formatCurrency(computePayslip(config, "").net_pay)}</p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          {open ? <ChevronDown className="h-4 w-4 text-gray-400" /> : <ChevronRight className="h-4 w-4 text-gray-400" />}
          <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); onRemove(); }}
            className="text-red-500 hover:text-red-700 h-7 w-7">
            <Trash2 className="h-3.5 w-3.5" />
          </Button>
        </div>
      </button>

      {open && (
        <div className="border-t border-gray-100 p-4 space-y-5">
          {/* Staff picker */}
          <div className="space-y-1.5">
            <Label className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Staff Member</Label>
            <Select value={config.teacher_id || "none"} onValueChange={(v) => {
              if (v === "none") return;
              const t = teachers.find((x) => x.id === v);
              onUpdate({ ...config, teacher_id: v, teacher_name: t ? `${t.first_name} ${t.last_name}` : config.teacher_name });
            }}>
              <SelectTrigger><SelectValue placeholder="Select staff" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="none">— select —</SelectItem>
                {teachers.map((t) => (
                  <SelectItem key={t.id} value={t.id}>{t.first_name} {t.last_name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Earnings */}
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Earnings (GH₵ / month)</p>
            <div className="grid grid-cols-2 gap-3">
              {[
                ["Basic Salary *", "basic_salary"],
                ["Transport", "transport_allowance"],
                ["Housing", "housing_allowance"],
                ["Medical", "medical_allowance"],
                ["Responsibility", "responsibility_allowance"],
                ["Other Allowance", "other_allowance"],
              ].map(([label, key]) => (
                <div key={key} className="space-y-1">
                  <Label className="text-xs text-gray-500">{label}</Label>
                  <Input type="number" min="0" step="0.01"
                    value={(config as unknown as Record<string, number>)[key] || ""}
                    onChange={(e) => set(key as keyof PayrollConfig, parseFloat(e.target.value) || 0)} />
                </div>
              ))}
            </div>
          </div>

          {/* Statutory info (read-only) */}
          <div className="rounded-lg bg-green-50 border border-green-200 p-3 space-y-1 text-xs text-green-800">
            <p className="font-semibold">Statutory deductions (auto-computed)</p>
            <p>SSNIT Employee: 5.5% of basic = <strong>{formatCurrency(config.basic_salary * 0.055)}</strong></p>
            <p>SSNIT Employer: 13% of basic = <strong>{formatCurrency(config.basic_salary * 0.13)}</strong> (school bears)</p>
            <p>PAYE: computed on chargeable income per GRA 2024 graduated bands</p>
          </div>

          {/* Custom deductions */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Local / Custom Deductions</p>
              <Button variant="outline" size="sm" onClick={addDeduction}>
                <Plus className="h-3 w-3 mr-1" /> Add
              </Button>
            </div>
            {(config.custom_deductions ?? []).length === 0 ? (
              <p className="text-xs text-gray-400">No custom deductions yet. Examples: staff loan repayment, cooperative, union dues.</p>
            ) : (
              <div className="space-y-2">
                {(config.custom_deductions ?? []).map((d) => (
                  <div key={d.id} className="flex items-center gap-2">
                    <Input placeholder="Label (e.g. Staff Loan)" value={d.label}
                      onChange={(e) => updateDeduction(d.id, { label: e.target.value })}
                      className="flex-1 h-8 text-sm" />
                    <Select value={d.type} onValueChange={(v) => updateDeduction(d.id, { type: v as "fixed" | "percent" })}>
                      <SelectTrigger className="w-24 h-8">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="fixed"><DollarSign className="inline h-3 w-3 mr-1" />Fixed</SelectItem>
                        <SelectItem value="percent"><Percent className="inline h-3 w-3 mr-1" />%</SelectItem>
                      </SelectContent>
                    </Select>
                    <Input type="number" min="0" step="0.01" value={d.value || ""}
                      onChange={(e) => updateDeduction(d.id, { value: parseFloat(e.target.value) || 0 })}
                      className="w-24 h-8 text-sm"
                      placeholder={d.type === "percent" ? "%" : "GH₵"} />
                    <Button variant="ghost" size="icon" onClick={() => removeDeduction(d.id)}
                      className="h-8 w-8 text-red-500 flex-shrink-0">
                      <X className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Payslip Preview Card ─────────────────────────────────────────
function PayslipCard({ ps, schoolName }: { ps: Payslip; schoolName: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-xl border border-gray-200 bg-white overflow-hidden">
      <button type="button" onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center gap-4 p-4 hover:bg-gray-50 cursor-pointer">
        <div className="flex-1 min-w-0 text-left">
          <p className="font-semibold text-sm text-gray-900">{ps.teacher_name}</p>
          <p className="text-xs text-gray-500">
            Gross {formatCurrency(ps.gross_pay)} · PAYE {formatCurrency(ps.paye)} · SSNIT {formatCurrency(ps.ssnit_employee)}
          </p>
        </div>
        <div className="flex items-center gap-3 flex-shrink-0">
          <span className="font-bold text-sm" style={{ color: "hsl(150 80% 24%)" }}>
            {formatCurrency(ps.net_pay)}
          </span>
          <Button variant="outline" size="sm" onClick={(e) => { e.stopPropagation(); printPayslip(ps, schoolName); }}>
            <Printer className="h-3.5 w-3.5 mr-1" /> Slip
          </Button>
          {open ? <ChevronDown className="h-4 w-4 text-gray-400" /> : <ChevronRight className="h-4 w-4 text-gray-400" />}
        </div>
      </button>

      {open && (
        <div className="border-t border-gray-100">
          <table className="w-full text-sm">
            <tbody>
              {ps.lines.map((line, i) => (
                <tr key={i} className="border-b border-gray-50 last:border-0">
                  <td className="px-4 py-2 text-gray-600">{line.label}</td>
                  <td className={`px-4 py-2 text-right font-medium ${
                    line.type === "deduction" ? "text-red-600" :
                    line.type === "employer_cost" ? "text-amber-700" :
                    line.type === "info" ? "font-bold text-gray-900" : ""
                  }`}>
                    {line.type === "deduction" ? `(${formatCurrency(line.amount)})` : formatCurrency(line.amount)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ── Main Page ────────────────────────────────────────────────────
export default function PayrollPage() {
  const [tab, setTab] = useState<"setup" | "run" | "history">("setup");
  const [configs, setConfigs] = useState<PayrollConfig[]>([]);
  const [teachers, setTeachers] = useState<Array<{ id: string; first_name: string; last_name: string }>>([]);
  const [schoolName, setSchoolName] = useState("School");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [running, setRunning] = useState(false);
  const [period, setPeriod] = useState(currentPeriod());
  const [lastRun, setLastRun] = useState<{ payslips: Payslip[]; period: string; total_net: number; total_employer_cost: number } | null>(null);
  const [history, setHistory] = useState<Array<{ date: string; period: string; teacher_name: string; net_pay: number; gross_pay: number; paye: number; ssnit_employee: number }>>([]);

  useEffect(() => {
    (async () => {
      try {
        const [cfgRes, tRes, sRes, expRes] = await Promise.all([
          fetch("/api/payroll"),
          fetch("/api/teachers?status=active"),
          fetch("/api/schools/me"),
          fetch("/api/expenses?category=salary&limit=500"),
        ]);
        const [cfgData, tData, sData, expData] = await Promise.all([cfgRes.json(), tRes.json(), sRes.json(), expRes.json()]);
        if (cfgRes.ok) setConfigs(cfgData.data ?? []);
        if (tRes.ok) setTeachers((tData.data ?? []).map((t: { id: string; first_name: string; last_name: string }) => ({ id: t.id, first_name: t.first_name, last_name: t.last_name })));
        if (sRes.ok) setSchoolName(sData.data?.name ?? "School");
        if (expRes.ok) {
          const runs = ((expData.data ?? []) as Array<{ date: string; description: string }>)
            .filter((e) => {
              try { const d = JSON.parse(e.description); return d._payroll === true; } catch { return false; }
            })
            .map((e) => {
              const d = JSON.parse(e.description);
              return { date: e.date, period: d.period, teacher_name: d.teacher_name, net_pay: d.net_pay, gross_pay: d.gross_pay, paye: d.paye, ssnit_employee: d.ssnit_employee };
            });
          setHistory(runs);
        }
      } catch { toast.error("Failed to load payroll data"); }
      finally { setLoading(false); }
    })();
  }, []);

  const saveConfigs = async () => {
    setSaving(true);
    try {
      const res = await fetch("/api/payroll", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ configs }),
      });
      if (!res.ok) { const d = await res.json(); toast.error(d.error || "Failed to save"); return; }
      toast.success("Payroll profiles saved");
    } catch { toast.error("Network error"); }
    finally { setSaving(false); }
  };

  const runPayroll = async () => {
    setRunning(true);
    try {
      const res = await fetch("/api/payroll", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ period, month: monthValue(period) }),
      });
      const data = await res.json();
      if (!res.ok) { toast.error(data.error || "Failed to run payroll"); return; }
      setLastRun(data.data);
      toast.success(`Payroll run complete — ${formatCurrency(data.data.total_net)} net to ${data.data.payslips.length} staff`);
      setTab("run");
    } catch { toast.error("Network error"); }
    finally { setRunning(false); }
  };

  const addStaff = () => setConfigs((prev) => [...prev, {
    teacher_id: "", teacher_name: "New Staff",
    basic_salary: 0, transport_allowance: 0, housing_allowance: 0,
    medical_allowance: 0, responsibility_allowance: 0, other_allowance: 0,
    custom_deductions: [],
  }]);

  if (loading) {
    return <div className="p-6 space-y-4"><div className="h-8 bg-gray-200 rounded w-48 animate-pulse" /><div className="h-64 bg-gray-100 rounded-xl animate-pulse" /></div>;
  }

  return (
    <div className="p-6 space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>Payroll</h1>
          <p className="text-sm text-gray-500 mt-1">Ghana PAYE (GRA 2024) + SSNIT + local deductions — computed automatically</p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <Select value={period} onValueChange={setPeriod}>
            <SelectTrigger className="w-[200px]"><SelectValue /></SelectTrigger>
            <SelectContent>
              {MONTHS.map((m) => (
                <SelectItem key={m} value={`${m} ${new Date().getFullYear()}`}>{m} {new Date().getFullYear()}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button onClick={runPayroll} disabled={running || configs.length === 0}
            className="text-white" style={{ background: "hsl(150 80% 24%)" }}>
            {running ? "Running…" : <><Play className="h-4 w-4 mr-1" />Run Payroll</>}
          </Button>
        </div>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: "Staff on Payroll", value: configs.length, icon: Users, color: "hsl(150 80% 24%)" },
          { label: "Total Gross", value: formatCurrency(configs.reduce((s, c) => s + c.basic_salary + c.transport_allowance + c.housing_allowance + c.medical_allowance + c.responsibility_allowance + c.other_allowance, 0)), icon: DollarSign, color: "hsl(38 92% 50%)" },
          { label: "Est. Net Pay", value: formatCurrency(configs.reduce((s, c) => s + computePayslip(c, "").net_pay, 0)), icon: Wallet, color: "hsl(200 80% 45%)" },
          { label: "Est. Employer Cost", value: formatCurrency(configs.reduce((s, c) => s + computePayslip(c, "").total_employer_cost, 0)), icon: Wallet, color: "hsl(0 65% 55%)" },
        ].map(({ label, value, icon: Icon, color }) => (
          <Card key={label} className="stat-card">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg flex-shrink-0" style={{ background: `${color}18` }}>
                <Icon className="h-4 w-4" style={{ color }} />
              </div>
              <div className="min-w-0">
                <p className="text-lg font-bold text-gray-900 truncate">{value}</p>
                <p className="text-xs text-gray-500">{label}</p>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Tabs */}
      <div className="flex gap-1 rounded-xl border border-gray-200 p-1 bg-gray-50 w-fit">
        {[["setup","Setup"], ["run","Last Run"], ["history","History"]].map(([key, label]) => (
          <button key={key} type="button" onClick={() => setTab(key as typeof tab)}
            className={`px-4 py-2 text-sm font-medium rounded-lg transition-all cursor-pointer ${tab === key ? "bg-white shadow-sm text-gray-900" : "text-gray-500 hover:text-gray-700"}`}>
            {label}
          </button>
        ))}
      </div>

      {/* ── SETUP TAB ── */}
      {tab === "setup" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-600">Configure each staff member's salary and deductions. SSNIT and PAYE are computed automatically.</p>
            <div className="flex gap-2">
              <Button variant="outline" onClick={addStaff}>
                <Plus className="h-4 w-4 mr-1" /> Add Staff
              </Button>
              <Button onClick={saveConfigs} disabled={saving}
                style={{ background: "hsl(150 80% 24%)" }} className="text-white">
                {saving ? "Saving…" : "Save All Profiles"}
              </Button>
            </div>
          </div>

          {/* Ghana payroll info box */}
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 space-y-1">
            <p className="font-semibold">Ghana Statutory Rates (GRA 2024 / SSNIT Act 766)</p>
            <div className="grid sm:grid-cols-2 gap-x-8 text-xs mt-1 text-amber-800">
              <div>
                <p>• SSNIT Employee: <strong>5.5%</strong> of basic salary</p>
                <p>• SSNIT Employer: <strong>13%</strong> of basic salary (school bears)</p>
              </div>
              <div>
                <p>• PAYE Band 1: 0% up to GHS 490/mo</p>
                <p>• PAYE Band 2: 5% on next GHS 110</p>
                <p>• PAYE Band 3: 10% on next GHS 130</p>
                <p>• PAYE Band 4: 17.5% on next GHS 3,167</p>
                <p>• PAYE Band 5+: 25%–35% above that</p>
              </div>
            </div>
          </div>

          {configs.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <Users className="h-10 w-10 text-gray-300 mx-auto mb-3" />
                <p className="text-gray-500 font-medium">No staff payroll profiles yet</p>
                <p className="text-xs text-gray-400 mt-1">Click "Add Staff" to start.</p>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {configs.map((c, i) => (
                <StaffConfigCard
                  key={i}
                  config={c}
                  teachers={teachers}
                  onUpdate={(updated) => setConfigs((prev) => prev.map((x, j) => j === i ? updated : x))}
                  onRemove={() => setConfigs((prev) => prev.filter((_, j) => j !== i))}
                />
              ))}
            </div>
          )}
        </div>
      )}

      {/* ── RUN TAB ── */}
      {tab === "run" && (
        <div className="space-y-4">
          {!lastRun ? (
            <Card>
              <CardContent className="py-12 text-center">
                <Play className="h-10 w-10 text-gray-300 mx-auto mb-3" />
                <p className="text-gray-500 font-medium">No payroll run yet this session</p>
                <p className="text-xs text-gray-400 mt-1">Select a period and click "Run Payroll" above.</p>
              </CardContent>
            </Card>
          ) : (
            <>
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-bold" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
                  {lastRun.period} — {lastRun.payslips.length} payslips
                </h2>
                <div className="text-right">
                  <p className="text-xs text-gray-500">Total net pay</p>
                  <p className="text-xl font-bold" style={{ color: "hsl(150 80% 24%)" }}>{formatCurrency(lastRun.total_net)}</p>
                </div>
              </div>
              <div className="space-y-2">
                {lastRun.payslips.map((ps) => (
                  <PayslipCard key={ps.teacher_id} ps={ps} schoolName={schoolName} />
                ))}
              </div>
              <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 flex items-start gap-3">
                <Wallet className="h-5 w-5 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="font-semibold">Total employer cost: {formatCurrency(lastRun.total_employer_cost)}</p>
                  <p className="text-xs mt-0.5">This includes the school's SSNIT employer contribution (13% of each staff's basic). Net pay totals have been posted to Accounting as salary expenses.</p>
                </div>
              </div>
            </>
          )}
        </div>
      )}

      {/* ── HISTORY TAB ── */}
      {tab === "history" && (
        <Card>
          <CardHeader>
            <CardTitle>Payroll History</CardTitle>
            <CardDescription>All past salary runs recorded in Accounting</CardDescription>
          </CardHeader>
          <CardContent>
            {history.length === 0 ? (
              <p className="text-sm text-gray-500 text-center py-8">No payroll runs yet.</p>
            ) : (
              <table className="sk-table">
                <thead>
                  <tr>
                    <th>Period</th>
                    <th>Staff</th>
                    <th>Gross</th>
                    <th>PAYE</th>
                    <th>SSNIT</th>
                    <th className="text-right">Net Pay</th>
                  </tr>
                </thead>
                <tbody>
                  {history.map((h, i) => (
                    <tr key={i}>
                      <td className="font-medium text-gray-900">{h.period}</td>
                      <td>{h.teacher_name}</td>
                      <td>{formatCurrency(h.gross_pay)}</td>
                      <td className="text-red-600">{formatCurrency(h.paye)}</td>
                      <td className="text-red-600">{formatCurrency(h.ssnit_employee)}</td>
                      <td className="text-right font-bold" style={{ color: "hsl(150 80% 24%)" }}>{formatCurrency(h.net_pay)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
